//
// Generated by Bluespec Compiler, version 2017.04.beta1 (build 35065, 2017-04-17)
//
// On Mon Jun 18 16:53:10 IST 2018
//
//
// Ports:
// Name                         I/O  size props
// deq_serial5_get                O    32 reg
// RDY_deq_serial5_get            O     1 reg
// RDY_enq_serial5_put            O     1 reg
// CLK_clkinX5                    I     1 clock
// CLK                            I     1 clock
// RST_N                          I     1 reset
// enq_serial5_put                I    32 reg
// EN_enq_serial5_put             I     1
// EN_deq_serial5_get             I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkTop_fpga2(CLK_clkinX5,
		   CLK,
		   RST_N,

		   EN_deq_serial5_get,
		   deq_serial5_get,
		   RDY_deq_serial5_get,

		   enq_serial5_put,
		   EN_enq_serial5_put,
		   RDY_enq_serial5_put);
  input  CLK_clkinX5;
  input  CLK;
  input  RST_N;

  // actionvalue method deq_serial5_get
  input  EN_deq_serial5_get;
  output [31 : 0] deq_serial5_get;
  output RDY_deq_serial5_get;

  // action method enq_serial5_put
  input  [31 : 0] enq_serial5_put;
  input  EN_enq_serial5_put;
  output RDY_enq_serial5_put;

  // signals for module outputs
  wire [31 : 0] deq_serial5_get;
  wire RDY_deq_serial5_get, RDY_enq_serial5_put;

  // ports of submodule noc
  wire [31 : 0] noc$recv_ports_5_getFlit,
		noc$recv_ports_6_getFlit,
		noc$send_ports_0_putFlit_flit_in,
		noc$send_ports_1_putFlit_flit_in,
		noc$send_ports_2_putFlit_flit_in,
		noc$send_ports_3_putFlit_flit_in,
		noc$send_ports_4_putFlit_flit_in,
		noc$send_ports_5_putFlit_flit_in,
		noc$send_ports_6_putFlit_flit_in,
		noc$send_ports_7_putFlit_flit_in,
		noc$send_ports_8_putFlit_flit_in;
  wire [1 : 0] noc$recv_ports_0_putNonFullVCs_nonFullVCs,
	       noc$recv_ports_1_putNonFullVCs_nonFullVCs,
	       noc$recv_ports_2_putNonFullVCs_nonFullVCs,
	       noc$recv_ports_3_putNonFullVCs_nonFullVCs,
	       noc$recv_ports_4_putNonFullVCs_nonFullVCs,
	       noc$recv_ports_5_putNonFullVCs_nonFullVCs,
	       noc$recv_ports_6_putNonFullVCs_nonFullVCs,
	       noc$recv_ports_7_putNonFullVCs_nonFullVCs,
	       noc$recv_ports_8_putNonFullVCs_nonFullVCs,
	       noc$send_ports_5_getNonFullVCs,
	       noc$send_ports_6_getNonFullVCs;
  wire noc$EN_recv_ports_0_getFlit,
       noc$EN_recv_ports_0_putNonFullVCs,
       noc$EN_recv_ports_1_getFlit,
       noc$EN_recv_ports_1_putNonFullVCs,
       noc$EN_recv_ports_2_getFlit,
       noc$EN_recv_ports_2_putNonFullVCs,
       noc$EN_recv_ports_3_getFlit,
       noc$EN_recv_ports_3_putNonFullVCs,
       noc$EN_recv_ports_4_getFlit,
       noc$EN_recv_ports_4_putNonFullVCs,
       noc$EN_recv_ports_5_getFlit,
       noc$EN_recv_ports_5_putNonFullVCs,
       noc$EN_recv_ports_6_getFlit,
       noc$EN_recv_ports_6_putNonFullVCs,
       noc$EN_recv_ports_7_getFlit,
       noc$EN_recv_ports_7_putNonFullVCs,
       noc$EN_recv_ports_8_getFlit,
       noc$EN_recv_ports_8_putNonFullVCs,
       noc$EN_send_ports_0_getNonFullVCs,
       noc$EN_send_ports_0_putFlit,
       noc$EN_send_ports_1_getNonFullVCs,
       noc$EN_send_ports_1_putFlit,
       noc$EN_send_ports_2_getNonFullVCs,
       noc$EN_send_ports_2_putFlit,
       noc$EN_send_ports_3_getNonFullVCs,
       noc$EN_send_ports_3_putFlit,
       noc$EN_send_ports_4_getNonFullVCs,
       noc$EN_send_ports_4_putFlit,
       noc$EN_send_ports_5_getNonFullVCs,
       noc$EN_send_ports_5_putFlit,
       noc$EN_send_ports_6_getNonFullVCs,
       noc$EN_send_ports_6_putFlit,
       noc$EN_send_ports_7_getNonFullVCs,
       noc$EN_send_ports_7_putFlit,
       noc$EN_send_ports_8_getNonFullVCs,
       noc$EN_send_ports_8_putFlit;

  // ports of submodule nodes_5
  wire [31 : 0] nodes_5$getFlit,
		nodes_5$getFlitSoft_get,
		nodes_5$putFlitSoft_put,
		nodes_5$setRecvFlit_flit;
  wire [3 : 0] nodes_5$setRecvPortID_portid;
  wire [1 : 0] nodes_5$getRecvVCMask, nodes_5$setNonFullVC_vcmask;
  wire nodes_5$EN_getFlit,
       nodes_5$EN_getFlitSoft_get,
       nodes_5$EN_putFlitSoft_put,
       nodes_5$EN_setNonFullVC,
       nodes_5$EN_setRecvFlit,
       nodes_5$EN_setRecvPortID,
       nodes_5$RDY_getFlit,
       nodes_5$RDY_getFlitSoft_get,
       nodes_5$RDY_getRecvVCMask,
       nodes_5$RDY_putFlitSoft_put;

  // ports of submodule nodes_6
  wire [31 : 0] nodes_6$getFlit,
		nodes_6$putFlitSoft_put,
		nodes_6$setRecvFlit_flit;
  wire [3 : 0] nodes_6$setRecvPortID_portid;
  wire [1 : 0] nodes_6$getRecvVCMask, nodes_6$setNonFullVC_vcmask;
  wire nodes_6$EN_getFlit,
       nodes_6$EN_getFlitSoft_get,
       nodes_6$EN_putFlitSoft_put,
       nodes_6$EN_setNonFullVC,
       nodes_6$EN_setRecvFlit,
       nodes_6$EN_setRecvPortID,
       nodes_6$RDY_getFlit,
       nodes_6$RDY_getRecvVCMask;

  // ports of submodule xfpga5
  wire [31 : 0] xfpga5$deq_serial_get,
		xfpga5$enq_serial_put,
		xfpga5$rx_get,
		xfpga5$tx_put;
  wire xfpga5$EN_deq_serial_get,
       xfpga5$EN_enq_serial_put,
       xfpga5$EN_rx_get,
       xfpga5$EN_tx_put,
       xfpga5$RDY_deq_serial_get,
       xfpga5$RDY_enq_serial_put,
       xfpga5$RDY_rx_get,
       xfpga5$RDY_tx_put;

  // actionvalue method deq_serial5_get
  assign deq_serial5_get = xfpga5$deq_serial_get ;
  assign RDY_deq_serial5_get = xfpga5$RDY_deq_serial_get ;

  // action method enq_serial5_put
  assign RDY_enq_serial5_put = xfpga5$RDY_enq_serial_put ;

  // submodule noc
  mkNetworkSimple noc(.CLK(CLK),
		      .RST_N(RST_N),
		      .recv_ports_0_putNonFullVCs_nonFullVCs(noc$recv_ports_0_putNonFullVCs_nonFullVCs),
		      .recv_ports_1_putNonFullVCs_nonFullVCs(noc$recv_ports_1_putNonFullVCs_nonFullVCs),
		      .recv_ports_2_putNonFullVCs_nonFullVCs(noc$recv_ports_2_putNonFullVCs_nonFullVCs),
		      .recv_ports_3_putNonFullVCs_nonFullVCs(noc$recv_ports_3_putNonFullVCs_nonFullVCs),
		      .recv_ports_4_putNonFullVCs_nonFullVCs(noc$recv_ports_4_putNonFullVCs_nonFullVCs),
		      .recv_ports_5_putNonFullVCs_nonFullVCs(noc$recv_ports_5_putNonFullVCs_nonFullVCs),
		      .recv_ports_6_putNonFullVCs_nonFullVCs(noc$recv_ports_6_putNonFullVCs_nonFullVCs),
		      .recv_ports_7_putNonFullVCs_nonFullVCs(noc$recv_ports_7_putNonFullVCs_nonFullVCs),
		      .recv_ports_8_putNonFullVCs_nonFullVCs(noc$recv_ports_8_putNonFullVCs_nonFullVCs),
		      .send_ports_0_putFlit_flit_in(noc$send_ports_0_putFlit_flit_in),
		      .send_ports_1_putFlit_flit_in(noc$send_ports_1_putFlit_flit_in),
		      .send_ports_2_putFlit_flit_in(noc$send_ports_2_putFlit_flit_in),
		      .send_ports_3_putFlit_flit_in(noc$send_ports_3_putFlit_flit_in),
		      .send_ports_4_putFlit_flit_in(noc$send_ports_4_putFlit_flit_in),
		      .send_ports_5_putFlit_flit_in(noc$send_ports_5_putFlit_flit_in),
		      .send_ports_6_putFlit_flit_in(noc$send_ports_6_putFlit_flit_in),
		      .send_ports_7_putFlit_flit_in(noc$send_ports_7_putFlit_flit_in),
		      .send_ports_8_putFlit_flit_in(noc$send_ports_8_putFlit_flit_in),
		      .EN_send_ports_0_putFlit(noc$EN_send_ports_0_putFlit),
		      .EN_send_ports_0_getNonFullVCs(noc$EN_send_ports_0_getNonFullVCs),
		      .EN_send_ports_1_putFlit(noc$EN_send_ports_1_putFlit),
		      .EN_send_ports_1_getNonFullVCs(noc$EN_send_ports_1_getNonFullVCs),
		      .EN_send_ports_2_putFlit(noc$EN_send_ports_2_putFlit),
		      .EN_send_ports_2_getNonFullVCs(noc$EN_send_ports_2_getNonFullVCs),
		      .EN_send_ports_3_putFlit(noc$EN_send_ports_3_putFlit),
		      .EN_send_ports_3_getNonFullVCs(noc$EN_send_ports_3_getNonFullVCs),
		      .EN_send_ports_4_putFlit(noc$EN_send_ports_4_putFlit),
		      .EN_send_ports_4_getNonFullVCs(noc$EN_send_ports_4_getNonFullVCs),
		      .EN_send_ports_5_putFlit(noc$EN_send_ports_5_putFlit),
		      .EN_send_ports_5_getNonFullVCs(noc$EN_send_ports_5_getNonFullVCs),
		      .EN_send_ports_6_putFlit(noc$EN_send_ports_6_putFlit),
		      .EN_send_ports_6_getNonFullVCs(noc$EN_send_ports_6_getNonFullVCs),
		      .EN_send_ports_7_putFlit(noc$EN_send_ports_7_putFlit),
		      .EN_send_ports_7_getNonFullVCs(noc$EN_send_ports_7_getNonFullVCs),
		      .EN_send_ports_8_putFlit(noc$EN_send_ports_8_putFlit),
		      .EN_send_ports_8_getNonFullVCs(noc$EN_send_ports_8_getNonFullVCs),
		      .EN_recv_ports_0_getFlit(noc$EN_recv_ports_0_getFlit),
		      .EN_recv_ports_0_putNonFullVCs(noc$EN_recv_ports_0_putNonFullVCs),
		      .EN_recv_ports_1_getFlit(noc$EN_recv_ports_1_getFlit),
		      .EN_recv_ports_1_putNonFullVCs(noc$EN_recv_ports_1_putNonFullVCs),
		      .EN_recv_ports_2_getFlit(noc$EN_recv_ports_2_getFlit),
		      .EN_recv_ports_2_putNonFullVCs(noc$EN_recv_ports_2_putNonFullVCs),
		      .EN_recv_ports_3_getFlit(noc$EN_recv_ports_3_getFlit),
		      .EN_recv_ports_3_putNonFullVCs(noc$EN_recv_ports_3_putNonFullVCs),
		      .EN_recv_ports_4_getFlit(noc$EN_recv_ports_4_getFlit),
		      .EN_recv_ports_4_putNonFullVCs(noc$EN_recv_ports_4_putNonFullVCs),
		      .EN_recv_ports_5_getFlit(noc$EN_recv_ports_5_getFlit),
		      .EN_recv_ports_5_putNonFullVCs(noc$EN_recv_ports_5_putNonFullVCs),
		      .EN_recv_ports_6_getFlit(noc$EN_recv_ports_6_getFlit),
		      .EN_recv_ports_6_putNonFullVCs(noc$EN_recv_ports_6_putNonFullVCs),
		      .EN_recv_ports_7_getFlit(noc$EN_recv_ports_7_getFlit),
		      .EN_recv_ports_7_putNonFullVCs(noc$EN_recv_ports_7_putNonFullVCs),
		      .EN_recv_ports_8_getFlit(noc$EN_recv_ports_8_getFlit),
		      .EN_recv_ports_8_putNonFullVCs(noc$EN_recv_ports_8_putNonFullVCs),
		      .send_ports_0_getNonFullVCs(),
		      .send_ports_1_getNonFullVCs(),
		      .send_ports_2_getNonFullVCs(),
		      .send_ports_3_getNonFullVCs(),
		      .send_ports_4_getNonFullVCs(),
		      .send_ports_5_getNonFullVCs(noc$send_ports_5_getNonFullVCs),
		      .send_ports_6_getNonFullVCs(noc$send_ports_6_getNonFullVCs),
		      .send_ports_7_getNonFullVCs(),
		      .send_ports_8_getNonFullVCs(),
		      .recv_ports_0_getFlit(),
		      .recv_ports_1_getFlit(),
		      .recv_ports_2_getFlit(),
		      .recv_ports_3_getFlit(),
		      .recv_ports_4_getFlit(),
		      .recv_ports_5_getFlit(noc$recv_ports_5_getFlit),
		      .recv_ports_6_getFlit(noc$recv_ports_6_getFlit),
		      .recv_ports_7_getFlit(),
		      .recv_ports_8_getFlit(),
		      .recv_ports_info_0_getRecvPortID(),
		      .recv_ports_info_1_getRecvPortID(),
		      .recv_ports_info_2_getRecvPortID(),
		      .recv_ports_info_3_getRecvPortID(),
		      .recv_ports_info_4_getRecvPortID(),
		      .recv_ports_info_5_getRecvPortID(),
		      .recv_ports_info_6_getRecvPortID(),
		      .recv_ports_info_7_getRecvPortID(),
		      .recv_ports_info_8_getRecvPortID());

  // submodule nodes_5
  mkNodeTask_fpga2_5 #(.portid(4'd5)) nodes_5(.CLK(CLK),
					      .RST_N(RST_N),
					      .putFlitSoft_put(nodes_5$putFlitSoft_put),
					      .setNonFullVC_vcmask(nodes_5$setNonFullVC_vcmask),
					      .setRecvFlit_flit(nodes_5$setRecvFlit_flit),
					      .setRecvPortID_portid(nodes_5$setRecvPortID_portid),
					      .EN_getFlit(nodes_5$EN_getFlit),
					      .EN_setNonFullVC(nodes_5$EN_setNonFullVC),
					      .EN_setRecvFlit(nodes_5$EN_setRecvFlit),
					      .EN_setRecvPortID(nodes_5$EN_setRecvPortID),
					      .EN_putFlitSoft_put(nodes_5$EN_putFlitSoft_put),
					      .EN_getFlitSoft_get(nodes_5$EN_getFlitSoft_get),
					      .getFlit(nodes_5$getFlit),
					      .RDY_getFlit(nodes_5$RDY_getFlit),
					      .RDY_setNonFullVC(),
					      .RDY_setRecvFlit(),
					      .getRecvVCMask(nodes_5$getRecvVCMask),
					      .RDY_getRecvVCMask(nodes_5$RDY_getRecvVCMask),
					      .RDY_setRecvPortID(),
					      .RDY_putFlitSoft_put(nodes_5$RDY_putFlitSoft_put),
					      .getFlitSoft_get(nodes_5$getFlitSoft_get),
					      .RDY_getFlitSoft_get(nodes_5$RDY_getFlitSoft_get));

  // submodule nodes_6
  mkNodeTask_echo2 #(.portid(4'd6)) nodes_6(.CLK(CLK),
					    .RST_N(RST_N),
					    .putFlitSoft_put(nodes_6$putFlitSoft_put),
					    .setNonFullVC_vcmask(nodes_6$setNonFullVC_vcmask),
					    .setRecvFlit_flit(nodes_6$setRecvFlit_flit),
					    .setRecvPortID_portid(nodes_6$setRecvPortID_portid),
					    .EN_getFlit(nodes_6$EN_getFlit),
					    .EN_setNonFullVC(nodes_6$EN_setNonFullVC),
					    .EN_setRecvFlit(nodes_6$EN_setRecvFlit),
					    .EN_setRecvPortID(nodes_6$EN_setRecvPortID),
					    .EN_putFlitSoft_put(nodes_6$EN_putFlitSoft_put),
					    .EN_getFlitSoft_get(nodes_6$EN_getFlitSoft_get),
					    .getFlit(nodes_6$getFlit),
					    .RDY_getFlit(nodes_6$RDY_getFlit),
					    .RDY_setNonFullVC(),
					    .RDY_setRecvFlit(),
					    .getRecvVCMask(nodes_6$getRecvVCMask),
					    .RDY_getRecvVCMask(nodes_6$RDY_getRecvVCMask),
					    .RDY_setRecvPortID(),
					    .RDY_putFlitSoft_put(),
					    .getFlitSoft_get(),
					    .RDY_getFlitSoft_get());

  // submodule xfpga5
  mkInterFPGA_LVDS xfpga5(.instnum(3'd5),
			  .CLK_clkinB(CLK_clkinX5),
			  .CLK_clkinA(CLK),
			  .reset_A(RST_N),
			  .enq_serial_put(xfpga5$enq_serial_put),
			  .tx_put(xfpga5$tx_put),
			  .EN_tx_put(xfpga5$EN_tx_put),
			  .EN_rx_get(xfpga5$EN_rx_get),
			  .EN_deq_serial_get(xfpga5$EN_deq_serial_get),
			  .EN_enq_serial_put(xfpga5$EN_enq_serial_put),
			  .RDY_tx_put(xfpga5$RDY_tx_put),
			  .rx_get(xfpga5$rx_get),
			  .RDY_rx_get(xfpga5$RDY_rx_get),
			  .deq_serial_get(xfpga5$deq_serial_get),
			  .RDY_deq_serial_get(xfpga5$RDY_deq_serial_get),
			  .RDY_enq_serial_put(xfpga5$RDY_enq_serial_put));

  // submodule noc
  assign noc$recv_ports_0_putNonFullVCs_nonFullVCs = 2'h0 ;
  assign noc$recv_ports_1_putNonFullVCs_nonFullVCs = 2'h0 ;
  assign noc$recv_ports_2_putNonFullVCs_nonFullVCs = 2'h0 ;
  assign noc$recv_ports_3_putNonFullVCs_nonFullVCs = 2'h0 ;
  assign noc$recv_ports_4_putNonFullVCs_nonFullVCs = 2'h0 ;
  assign noc$recv_ports_5_putNonFullVCs_nonFullVCs = nodes_5$getRecvVCMask ;
  assign noc$recv_ports_6_putNonFullVCs_nonFullVCs = nodes_6$getRecvVCMask ;
  assign noc$recv_ports_7_putNonFullVCs_nonFullVCs = 2'h0 ;
  assign noc$recv_ports_8_putNonFullVCs_nonFullVCs = 2'h0 ;
  assign noc$send_ports_0_putFlit_flit_in = 32'h0 ;
  assign noc$send_ports_1_putFlit_flit_in = 32'h0 ;
  assign noc$send_ports_2_putFlit_flit_in = 32'h0 ;
  assign noc$send_ports_3_putFlit_flit_in = 32'h0 ;
  assign noc$send_ports_4_putFlit_flit_in = 32'h0 ;
  assign noc$send_ports_5_putFlit_flit_in = nodes_5$getFlit ;
  assign noc$send_ports_6_putFlit_flit_in = nodes_6$getFlit ;
  assign noc$send_ports_7_putFlit_flit_in = 32'h0 ;
  assign noc$send_ports_8_putFlit_flit_in = 32'h0 ;
  assign noc$EN_send_ports_0_putFlit = 1'b0 ;
  assign noc$EN_send_ports_0_getNonFullVCs = 1'b0 ;
  assign noc$EN_send_ports_1_putFlit = 1'b0 ;
  assign noc$EN_send_ports_1_getNonFullVCs = 1'b0 ;
  assign noc$EN_send_ports_2_putFlit = 1'b0 ;
  assign noc$EN_send_ports_2_getNonFullVCs = 1'b0 ;
  assign noc$EN_send_ports_3_putFlit = 1'b0 ;
  assign noc$EN_send_ports_3_getNonFullVCs = 1'b0 ;
  assign noc$EN_send_ports_4_putFlit = 1'b0 ;
  assign noc$EN_send_ports_4_getNonFullVCs = 1'b0 ;
  assign noc$EN_send_ports_5_putFlit = nodes_5$RDY_getFlit ;
  assign noc$EN_send_ports_5_getNonFullVCs = 1'd1 ;
  assign noc$EN_send_ports_6_putFlit = nodes_6$RDY_getFlit ;
  assign noc$EN_send_ports_6_getNonFullVCs = 1'd1 ;
  assign noc$EN_send_ports_7_putFlit = 1'b0 ;
  assign noc$EN_send_ports_7_getNonFullVCs = 1'b0 ;
  assign noc$EN_send_ports_8_putFlit = 1'b0 ;
  assign noc$EN_send_ports_8_getNonFullVCs = 1'b0 ;
  assign noc$EN_recv_ports_0_getFlit = 1'b0 ;
  assign noc$EN_recv_ports_0_putNonFullVCs = 1'b0 ;
  assign noc$EN_recv_ports_1_getFlit = 1'b0 ;
  assign noc$EN_recv_ports_1_putNonFullVCs = 1'b0 ;
  assign noc$EN_recv_ports_2_getFlit = 1'b0 ;
  assign noc$EN_recv_ports_2_putNonFullVCs = 1'b0 ;
  assign noc$EN_recv_ports_3_getFlit = 1'b0 ;
  assign noc$EN_recv_ports_3_putNonFullVCs = 1'b0 ;
  assign noc$EN_recv_ports_4_getFlit = 1'b0 ;
  assign noc$EN_recv_ports_4_putNonFullVCs = 1'b0 ;
  assign noc$EN_recv_ports_5_getFlit = 1'd1 ;
  assign noc$EN_recv_ports_5_putNonFullVCs = nodes_5$RDY_getRecvVCMask ;
  assign noc$EN_recv_ports_6_getFlit = 1'd1 ;
  assign noc$EN_recv_ports_6_putNonFullVCs = nodes_6$RDY_getRecvVCMask ;
  assign noc$EN_recv_ports_7_getFlit = 1'b0 ;
  assign noc$EN_recv_ports_7_putNonFullVCs = 1'b0 ;
  assign noc$EN_recv_ports_8_getFlit = 1'b0 ;
  assign noc$EN_recv_ports_8_putNonFullVCs = 1'b0 ;

  // submodule nodes_5
  assign nodes_5$putFlitSoft_put = xfpga5$rx_get ;
  assign nodes_5$setNonFullVC_vcmask = noc$send_ports_5_getNonFullVCs ;
  assign nodes_5$setRecvFlit_flit = noc$recv_ports_5_getFlit ;
  assign nodes_5$setRecvPortID_portid = 4'h0 ;
  assign nodes_5$EN_getFlit = nodes_5$RDY_getFlit ;
  assign nodes_5$EN_setNonFullVC = 1'd1 ;
  assign nodes_5$EN_setRecvFlit = 1'd1 ;
  assign nodes_5$EN_setRecvPortID = 1'b0 ;
  assign nodes_5$EN_putFlitSoft_put =
	     xfpga5$RDY_rx_get && nodes_5$RDY_putFlitSoft_put ;
  assign nodes_5$EN_getFlitSoft_get =
	     xfpga5$RDY_tx_put && nodes_5$RDY_getFlitSoft_get ;

  // submodule nodes_6
  assign nodes_6$putFlitSoft_put = 32'h0 ;
  assign nodes_6$setNonFullVC_vcmask = noc$send_ports_6_getNonFullVCs ;
  assign nodes_6$setRecvFlit_flit = noc$recv_ports_6_getFlit ;
  assign nodes_6$setRecvPortID_portid = 4'h0 ;
  assign nodes_6$EN_getFlit = nodes_6$RDY_getFlit ;
  assign nodes_6$EN_setNonFullVC = 1'd1 ;
  assign nodes_6$EN_setRecvFlit = 1'd1 ;
  assign nodes_6$EN_setRecvPortID = 1'b0 ;
  assign nodes_6$EN_putFlitSoft_put = 1'b0 ;
  assign nodes_6$EN_getFlitSoft_get = 1'b0 ;

  // submodule xfpga5
  assign xfpga5$enq_serial_put = enq_serial5_put ;
  assign xfpga5$tx_put = nodes_5$getFlitSoft_get ;
  assign xfpga5$EN_tx_put = xfpga5$RDY_tx_put && nodes_5$RDY_getFlitSoft_get ;
  assign xfpga5$EN_rx_get = xfpga5$RDY_rx_get && nodes_5$RDY_putFlitSoft_put ;
  assign xfpga5$EN_deq_serial_get = EN_deq_serial5_get ;
  assign xfpga5$EN_enq_serial_put = EN_enq_serial5_put ;
endmodule  // mkTop_fpga2

