# TCL File Generated by Component Editor 16.1
# Tue Jun 19 15:11:10 IST 2018
# DO NOT MODIFY


# 
# echo_fpga12_component "echo_fpga12_component" v1.0
#  2018.06.19.15:11:10
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module echo_fpga12_component
# 
set_module_property DESCRIPTION ""
set_module_property NAME echo_fpga12_component
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME echo_fpga12_component
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL FPGA12_TopNiosInterface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file BRAM1.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/BRAM1.v
add_fileset_file BRAM1BE.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/BRAM1BE.v
add_fileset_file BRAM1BELoad.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/BRAM1BELoad.v
add_fileset_file BRAM1Load.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/BRAM1Load.v
add_fileset_file BRAM2.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/BRAM2.v
add_fileset_file BRAM2BE.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/BRAM2BE.v
add_fileset_file BRAM2BELoad.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/BRAM2BELoad.v
add_fileset_file BRAM2Load.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/BRAM2Load.v
add_fileset_file Bram.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/Bram.v
add_fileset_file FIFO1.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/FIFO1.v
add_fileset_file FIFO10.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/FIFO10.v
add_fileset_file FIFO2.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/FIFO2.v
add_fileset_file RegFile.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/RegFile.v
add_fileset_file RegFileLoadSyn.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/RegFileLoadSyn.v
add_fileset_file RegFile_1port.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/RegFile_1port.v
add_fileset_file RevertReg.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/RevertReg.v
add_fileset_file SizedFIFO.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/SizedFIFO.v
add_fileset_file SyncFIFO1.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/SyncFIFO1.v
add_fileset_file connect_parameters.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/connect_parameters.v
add_fileset_file customdb72c8b4c5f5588943c5ff029a85054c_8RTs_2VCs_8BD_25DW_SepIFRoundRobinAlloc_routing_0.hex HEX PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/customdb72c8b4c5f5588943c5ff029a85054c_8RTs_2VCs_8BD_25DW_SepIFRoundRobinAlloc_routing_0.hex
add_fileset_file customdb72c8b4c5f5588943c5ff029a85054c_8RTs_2VCs_8BD_25DW_SepIFRoundRobinAlloc_routing_1.hex HEX PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/customdb72c8b4c5f5588943c5ff029a85054c_8RTs_2VCs_8BD_25DW_SepIFRoundRobinAlloc_routing_1.hex
add_fileset_file customdb72c8b4c5f5588943c5ff029a85054c_8RTs_2VCs_8BD_25DW_SepIFRoundRobinAlloc_routing_2.hex HEX PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/customdb72c8b4c5f5588943c5ff029a85054c_8RTs_2VCs_8BD_25DW_SepIFRoundRobinAlloc_routing_2.hex
add_fileset_file customdb72c8b4c5f5588943c5ff029a85054c_8RTs_2VCs_8BD_25DW_SepIFRoundRobinAlloc_routing_3.hex HEX PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/customdb72c8b4c5f5588943c5ff029a85054c_8RTs_2VCs_8BD_25DW_SepIFRoundRobinAlloc_routing_3.hex
add_fileset_file mkCnctBridge.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/mkCnctBridge.v
add_fileset_file mkIQRouterCoreSimple.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/mkIQRouterCoreSimple.v
add_fileset_file mkInputArbiter.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/mkInputArbiter.v
add_fileset_file mkInputQueue.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/mkInputQueue.v
add_fileset_file mkInterFPGA_LVDS.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/mkInterFPGA_LVDS.v
add_fileset_file mkMFpgaTop.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/mkMFpgaTop.v
add_fileset_file mkNetworkSimple.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/mkNetworkSimple.v
add_fileset_file mkNodeTask_echo1.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/mkNodeTask_echo1.v
add_fileset_file mkNodeTask_echo2.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/mkNodeTask_echo2.v
add_fileset_file mkNodeTask_fpga1_4.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/mkNodeTask_fpga1_4.v
add_fileset_file mkNodeTask_fpga2_5.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/mkNodeTask_fpga2_5.v
add_fileset_file mkNodeTask_host.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/mkNodeTask_host.v
add_fileset_file mkOutPortFIFO.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/mkOutPortFIFO.v
add_fileset_file mkOutputArbiter.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/mkOutputArbiter.v
add_fileset_file mkRouterInputArbitersRoundRobin.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/mkRouterInputArbitersRoundRobin.v
add_fileset_file mkRouterInputArbitersStatic.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/mkRouterInputArbitersStatic.v
add_fileset_file mkRouterOutputArbitersRoundRobin.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/mkRouterOutputArbitersRoundRobin.v
add_fileset_file mkRouterOutputArbitersStatic.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/mkRouterOutputArbitersStatic.v
add_fileset_file mkSepRouterAllocator.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/mkSepRouterAllocator.v
add_fileset_file mkTb.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/mkTb.v
add_fileset_file mkTop_fpga1.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/mkTop_fpga1.v
add_fileset_file mkTop_fpga2.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/mkTop_fpga2.v
add_fileset_file module_gen_grant_carry.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/module_gen_grant_carry.v
add_fileset_file module_outport_encoder.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/module_outport_encoder.v
add_fileset_file tb.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/tb.v
add_fileset_file FPGA12_TopNiosInterface.v VERILOG PATH MTP_work/LVDS/ECHO_FPGA12/src_files_2/FPGA12_TopNiosInterface.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock CLK clk Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitStates 0
set_interface_property avalon_slave_0 readWaitTime 0
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 address address Input 3
add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 readdata readdata Output 32
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 writedata writedata Input 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink RST_N reset_n Input 1


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint avalon_slave_0
set_interface_property interrupt_sender associatedClock clock
set_interface_property interrupt_sender associatedReset reset_sink
set_interface_property interrupt_sender bridgedReceiverOffset ""
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender irq irq Output 1

